### ISSUE TITLE
Grove Beginner Kit OLED

### ISSUE THREAD

**Issue by Uppermill** [technologiescollege/BlocklyArduino_AIO#4]
Seb

I have had problems getting the OLED display in the Grove Beginner Kit to work.

In the end I had to change the constructor line from

U8X8_SSD1306_128X64_ALT0_HW_I2C u8x8(/* reset=*/ U8X8_PIN_NONE);

to

U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(SCL,SDA, U8X8_PIN_NONE);

Allan

**Comment by SebCanet** [comment]
Fixed!
Could you try, please?

**Comment by Uppermill** [comment]
I am not certain that I am accessing the change you have made. I downloaded the latest release again but I still get the same problem. Can you tell me what I need to do to test the new version?

**Comment by Uppermill** [comment]
So, I worked out that I had to do the download from the green Code button which I have done. After white listing the serial.discovery.exe program, I now get the same error as detailed in the issue that is currently open - Several Cards Detected.

**Comment by SebCanet** [comment]
Sorry, I did not explain rightfully... You just have to replace the file BlocklyArduino_AIO\B@electron\www\generators\arduino\grove_beginner_kit.js with the one in repo.

And about COM port, you can force it in BlocklyArduino.ini file. I'll download a W10x86 Familial to answer your other issue.

**Comment by Uppermill** [comment]
On the file downloaded from the Code button, I am still unable to get the program to start. I have updated the .ini file with the correct COM port "3" but that still causes the program to terminate.

I managed to restore the old version and substitute the .js file with the new version, but when I press the Source Code button, I get this error message
![ab_error](https://user-images.githubusercontent.com/18369444/107376858-46541200-6ae2-11eb-9373-1b06ebc3cf66.png)
